# Generated by Django 5.0.7 on 2024-07-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthIdentifier",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("identifier", models.CharField()),
            ],
        ),
    ]
