# Generated by Django 5.0.7 on 2024-07-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_oauthidentifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdepressiontest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userinfertility",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="depression_test",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="users.userdepressiontest",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="infertility",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="users.userinfertility",
            ),
        ),
    ]
