# Generated by Django 5.0.7 on 2024-08-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userinfertility_care_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OAuthIdentifier",
        ),
        migrations.AlterField(
            model_name="userdepressiontest",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userinfertility",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
