version: '3.8'

services:
  webloom-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    environment:
      - DEBUG=1
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
