# Generated by Django 5.0.7 on 2024-07-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloomFeedback",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("content", models.CharField(db_comment="피드백 내용", max_length=500)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="피드백 생성일"),
                ),
            ],
        ),
    ]
