# Generated by Django 5.0.7 on 2024-07-20 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bloom_ai", "0001_initial"),
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloomfeedback",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloom_feedbacks",
                to="question.question",
            ),
        ),
    ]
