# Generated by Django 5.0.7 on 2024-07-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloom_ai", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloomfeedback",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
