# Generated by Django 5.0.7 on 2024-07-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloom_ai", "0003_alter_bloomfeedback_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloomfeedback",
            name="content",
            field=models.CharField(db_comment="피드백 내용", max_length=1000),
        ),
    ]
