# Generated by Django 5.0.7 on 2024-07-20 01:49

import app.enum
import app.orm
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("content", models.CharField(db_comment="질문 내용", max_length=500)),
                ("female_audio_url", models.URLField(db_comment="아내 음성 데이터 URL")),
                ("male_audio_url", models.URLField(db_comment="남편 음성 데이터 URL")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="매칭 체결일"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="match.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("content", models.CharField(db_comment="마음 게시글 본문", max_length=500)),
                ("emotion", app.orm.TextEnumField(enum=app.enum.Emotion)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_answers",
                        to="question.question",
                    ),
                ),
            ],
        ),
    ]
