# Generated by Django 5.0.7 on 2024-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_alter_question_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="female_audio_url",
            field=models.URLField(db_comment="아내 음성 데이터 URL", null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="male_audio_url",
            field=models.URLField(db_comment="남편 음성 데이터 URL", null=True),
        ),
    ]
