# Generated by Django 5.0.7 on 2024-07-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0005_alter_questionanswer_content_alter_questionanswer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="마음 작성일", null=True
            ),
        ),
    ]
