# Generated by Django 5.0.7 on 2024-07-27 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_questionanswer_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(db_comment='마음 댓글 내용', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='마음 댓글 작성일')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
