# Generated by Django 5.0.7 on 2024-07-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0006_questionanswer_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswer",
            name="emotion",
            field=models.CharField(max_length=10),
        ),
    ]
