# Generated by Django 5.0.7 on 2024-08-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_alter_questionanswer_emotion'),
        ('question', '0007_questioncomment'),
    ]

    operations = [
    ]
