# Generated by Django 5.0.7 on 2024-08-03 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0008_merge_20240802_0536"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="questioncomment",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_comment",
                to="question.question",
            ),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_answers",
                to="question.question",
            ),
        ),
        migrations.AlterField(
            model_name="questioncomment",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_question_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
