# Generated by Django 5.0.7 on 2024-07-23 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("question", "0005_alter_questionanswer_content_alter_questionanswer_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("content", models.CharField(db_comment="사용자 답변 내용", max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="답변 작성일"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_comment="질문",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="question.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="답변 작성자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
