# Generated by Django 5.0.7 on 2024-07-20 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("match", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitecode",
            name="creator",
            field=models.ForeignKey(
                db_comment="생성한 유저",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="female",
            field=models.ForeignKey(
                db_comment="아내",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="female",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="male",
            field=models.ForeignKey(
                db_comment="남편",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="male",
                to="users.user",
            ),
        ),
    ]
