# Generated by Django 5.0.7 on 2024-07-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="code",
            field=models.CharField(
                db_comment="초대 코드", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="invitecode",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
